# === БАЗА ===
currency_code: 5
steam_fee_pct: 15
min_daily_sales: 1

# Старые алерты "Δ за интервал" — можно оставить выключенными
enable_change_alerts: false
change_percent_threshold: 10
cooldown_hours: 6

# === ДОЛГИЕ СИГНАЛЫ (как было) ===
signals:
  price_from_7d_median:
    soft_pct: 0.90
    deep_pct: 0.85
    min_points: 12

  volume_spike:
    spike_multiplier: 1.5
    min_points: 12

  combo_cooldown_hours: 6

  # === НОВОЕ: ПАМП-КОНТРОЛЬ (короткое окно) ===
  pump:
    short_window_minutes: 120   # окно для быстрой базы (90–120 мин самое то)
    min_points: 4               # мин. число точек в коротком окне

    price_jump_pct: 0.08        # медиана ≥ база_short × (1 + 8%) → джамп
    ask_jump_pct:   0.10        # ask    ≥ база_short × (1 + 10%) → джамп
    breakout_points: 6          # новая вершина vs последние N точек
    breakout_extra_pct: 0.03    # запас к локальному максимуму (3%)

    momentum_mult: 1.8          # текущий темп продаж ≥ base_hourly × 1.8
    confirm_price_pct: 0.04     # +4% к предыдущей медиане — для подтверждения момента
    cooldown_minutes: 60        # антиспам для "pump" (мин.)

# === ОБЛАСТЬ МОНИТОРИНГА ===
scope:
  event: "Austin 2025"
  teams:
    include:
      - "Team Spirit"
      - "Team Liquid"
      - "TYLOO"
      - "Lynn Vision"
      - "Aurora"
      - "MOUZ"
      - "Complexity"
      - "FlyQuest"
      - "OG"
      - "Falcons"
    variants: ["paper","holo","foil"]
  players:
    include:
      - "m0NESY"
      - "donk"
      - "NiKo"
      - "Lucky"
      - "exit"
      - "zont1x"
      - "ropz"
      - "JamYoung"
      - "Jee"
      - "z4kr"
    variants: ["paper","holo","foil"]

aliases:
  players:
    monesy: "m0NESY"
    niko: "NiKo"
    zontix: "zont1x"
    jamyoung: "JamYoung"
    jee: "Jee"

# === СЕТЕВЫЕ НАСТРОЙКИ / АНТИ-БАН ===
request:
  base_delay_sec: 2.5
  jitter_sec: 0.5
  retries: 5
  backoff_factor: 1.8
  shuffle: true
