name: CS2 Monitor v3 (Austin 2025)

on:
  schedule:
    - cron: "*/60 * * * *"   # каждые 60 минут
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: .state
          key: cs2-monitor-state-${{ github.run_id }}
          restore-keys: |
            cs2-monitor-state-

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Run monitor
        run: python monitor.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
