name: CS2 Monitor v3 (Austin 2025)

on:
  schedule:
    - cron: "0 * * * *"   # каждый час, в 00 минут по UTC
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: cs2-monitor
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Heartbeat
        run: echo "Schedule fired at $(date -u) | ref=$GITHUB_REF | attempt=$GITHUB_RUN_ATTEMPT"

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Run monitor
        run: python monitor.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
